### ISSUE TITLE
Any demo code??

### ISSUE THREAD

**Issue by isra60** [ekosman/AnomalyDetectionCVPR2018-Pytorch#17]
Something like demo_GUI.py from the original repo.

Thanks.

**Comment by PHDPeter** [comment]
I am working on this (https://github.com/ekosman/AnomalyDetectionCVPR2018-Pytorch/issues/16) which should do what you want thou you would need a pertained wights to run with it.
I will make sure to put in a pull request when I have this "live_GUI" working :-)

**Comment by PHDPeter** [comment]
I have some demo code that will take any video and run the Anomaly Detection code (including CD3 feature extraction) and output a video with a graph of the Anomaly Detection prediction on the right-hand side (like in the demo code for the paper). It is all still a bit rough but it works and I do plan to add to it so I can always update later. 

I am a bit new to contributing to other people's GitHub so not sure what would be easier, just adding the code here or making a pull request.
I think the pull request would be best as I make a small change in the data_loader method in order to get it all to work, but what would you rather @ekosman :-)

**Comment by ekosman** [comment]
@PHDPeter This is wonderful!
PR would be great!

**Comment by ekosman** [comment]
@PHDPeter BTW, when you submit the PR, can you add a few lines to README (the command for running your script + your credit :) )
