### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jasper-cell** [ekosman/AnomalyDetectionCVPR2018-Pytorch#34]
hi,thank you for your code.but i have some errors in my runing code.   
When I use feature_extractor like your guide, but I meet some eror like:
    return self.cumulative_sizes[-1]
    IndexError: list index out of range
can you tell me why this error will happen

**Comment by ekosman** [comment]
Hi @jasper-cell and thanks for reporting this.

Currently, I'm working on V2 of this repo so it should be fully updated when I finish. It would probably take a while because I'm doing it all on my personal mac and it doesn't have a proper GPU.

Anyway, this error sounds different, so please, can you provide the command you use to run? Moreover, this is a torchvision related error so maybe the path you provide isn't right. Did you download the relevant dataset and provide the right path to the script?

**Comment by ekosman** [comment]
Merged a branch that fixes this
