### ISSUE TITLE
Training code is not using GPU 

### ISSUE THREAD

**Issue by cervantes-loves-ai** [ekosman/AnomalyDetectionCVPR2018-Pytorch#5]
tried different solutions but no response, even when ichanged batch size 1000 than also code still running and no difference in cpu or gpu. any solutions?

**Comment by 1senlin** [comment]
hi ， i test this model on some videos ,but the result is not good, do you have the same question? or you have a good result

**Comment by ekosman** [comment]
Do you have cuda enabled?
You should not change the batch size because it is tuned for the paper and matches the hard-coded length of the features loader (see features_loader.py line no.45)

You probably don't notice any difference since the training uses a small network. The heavy work here is done in the features extraction phase.
